FROM node:20-alpine

WORKDIR /app

# Copy all necessary files
COPY package*.json ./
COPY tsconfig.json ./
COPY src/ ./src/

# Install deps & build
RUN npm install && npm run build

# Use production dependencies only
# RUN npm prune --production

# Expose port
EXPOSE 3000

CMD ["node", "dist/app.js"]
